site_name: dbtvault-scalefree
site_author: Scalefree International GmbH
site_dir: 'site'
repo_name: 'ScalefreeCOM/dbtvault-scalefree'
site_url: 'https://dbtvault-scalefree.readthedocs.io/'
repo_url: 'https://github.com/ScalefreeCOM/dbtvault-scalefree'
dev_addr: 127.0.0.1:8001
theme:
    name: 'material'
    custom_dir: 'overrides'
    show_sidebar: true
    logo: 'media/images/scalefree_logo.svg'
    banner: 'assets/images/docs-banner.png'
    favicon: 'assets/images/favicon.ico'
    palette:
      - scheme: material
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    highlightjs: true
    features:
      - navigation.top
nav:
  - Home: 'index.md'
  - Tutorials:
      - Getting Started: 'tutorial/tut_getting_started.md'
      - Staging: 'tutorial/tut_staging.md'
      - Hubs: 'tutorial/tut_hubs.md'
      - Links: 'tutorial/tut_links.md'
      - Transactional Links: 'tutorial/tut_t_links.md'
      - Satellites: 'tutorial/tut_satellites.md'
      - Effectivity Satellites: 'tutorial/tut_eff_satellites.md'
      - Multi-Active Satellites: 'tutorial/tut_multi_active_satellites.md'
      - Extended Tracking Satellites: 'tutorial/tut_xts.md'
      - As of Date Tables: 'tutorial/tut_as_of_date.md'
      - Point In Time (PIT) tables: 'tutorial/tut_point_in_time.md'
      - Bridge Tables: 'tutorial/tut_bridges.md'
  - Worked example:
      - Getting Started: 'worked_example/we_worked_example.md'
      - Project setup: 'worked_example/we_setup.md'
      - Profiling TPC-H: 'worked_example/we_tpch_profile.md'
      - Creating the stage layers: 'worked_example/we_staging.md'
      - Loading the vault: 'worked_example/we_loading.md'
  - Metadata Reference: 'metadata.md'
  - Macros: 'macros.md'
  - Materialisations: 'materialisations.md'
  - Best Practices: 'best_practices.md'
  - Extending: 'extending.md'
  - Roadmap: 'roadmap.md'
  - Versions: 'versions.md'
  - Changelog:
      - Stable Releases: 'changelog/stable.md'
      - Beta Releases: 'changelog/beta.md'
  - Contributing:
    - Getting Started: 'contributing.md'
    - Style Guides:
        - Tutorials: 'style_guides/tutorials.md'
  - Licence: 'LICENSE.md'
  - Find Us:
      - GitHub: 'https://github.com/scalefreeCOM'
      - Twitter: 'https://twitter.com/scalefreecom?lang=en'
      - LinkedIn: 'https://www.linkedin.com/company/scalefree/'
      - Scalefree Website: 'https://www.scalefree.com/'

extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.scalefree.com'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ScalefreeCOM'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/scalefreecom'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/scalefree'

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
  - toc:
      permalink: true
      toc_depth: 1-3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/all.css'

copyright: Scalefree International GmbH - Data Vault 2.0 is a registered trademark of Dan Linstedt - dbt is a registered trademark of dbt labs
